# .pre-commit-config.yaml

# See https://pre-commit.com for more information
# Hooks help you automatically format and lint your code before committing

repos:
  # Pre-commit Hooks Repository
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: \.md$
      - id: check-added-large-files

  # Prettier for Formatting HTML
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
        name: Prettier file formatter
        files: \.(html|yaml)$
        types: [file]
        args: ["--write"]

  # mdformat for formatting markdown!
  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22 # Use the ref you want to point at
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-frontmatter
        args: ["--wrap", "79"]
